apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.service }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type | default "ClusterIP" }}
